import { LighterProduct, FinishDetails, FlameDetails, FontDetails, CustomerReview } from "./types";

export const FINISHES: FinishDetails[] = [
  {
    id: "gold",
    name: "24K Yellow Gold",
    colorHex: "#D4AF37",
    bgGradient: "from-[#F3E7C4] via-[#D4AF37] to-[#8B6F2B]",
    reflectionClass: "bg-gradient-to-tr from-white/10 via-white/40 to-transparent",
    description: "Solid brass plated in flawless 24-karat yellow gold with micro-diamond hand guilloché detailing. Iconic, timeless, and resonant.",
    priceModifier: 150,
  },
  {
    id: "obsidian",
    name: "Obsidian Titanium",
    colorHex: "#1C1C1B",
    bgGradient: "from-[#3A3A38] via-[#1C1C1B] to-[#0A0A0A]",
    reflectionClass: "bg-gradient-to-tr from-white/5 via-white/15 to-transparent",
    description: "Military-grade aerospace titanium alloy coated in dark physical vapor deposition (PVD) matte. Lightweight, indestructible, and modern.",
    priceModifier: 0,
  },
  {
    id: "silver",
    name: "925 Sterling Silver",
    colorHex: "#C0C0C0",
    bgGradient: "from-[#F2F2F2] via-[#C0C0C0] to-[#7F7F7F]",
    reflectionClass: "bg-gradient-to-tr from-white/20 via-white/50 to-transparent",
    description: "Solid 925 sterling silver with a master artisan-engraved rococo scroll pattern, meticulously hand-oxidized for dramatic depth.",
    priceModifier: 120,
  },
  {
    id: "emerald",
    name: "Imperial Emerald Urushi",
    colorHex: "#0F52BA",
    bgGradient: "from-[#105D38] via-[#0B3C23] to-[#041D0F]",
    reflectionClass: "bg-gradient-to-tr from-white/10 via-white/30 to-transparent",
    description: "Bespoke natural Urushi lacquer imported from Japan, layered and polished by hand over fifteen sessions, complete with gold powder accents.",
    priceModifier: 250,
  },
  {
    id: "damascus",
    name: "Cobalt Damascus Steel",
    colorHex: "#4F5D75",
    bgGradient: "from-[#7D8491] via-[#4F5D75] to-[#2D3142]",
    reflectionClass: "bg-gradient-to-tr from-white/10 via-white/25 to-transparent",
    description: "Individually forged 128-layer pattern-welded steel, acid-etched to reveal gorgeous organic fluid waves of absolute strength.",
    priceModifier: 180,
  },
];

export const FLAMES: FlameDetails[] = [
  {
    id: "candle",
    name: "Classical Ambient Flame",
    description: "A soft, yellow, slow-burning candle flame. Highly sensitive to movement, casting an elegant warm glow ideal for lighting premium cigars and candles.",
    colorHex: "#FFB03A",
    priceModifier: 0,
  },
  {
    id: "jet",
    name: "Hyper-Velocity Jet Torch",
    description: "A wind-resistant, high-temperature blue laser jet torch. Delivers focused, reliable ignition regardless of environmental draft or angle.",
    colorHex: "#3FA9FF",
    priceModifier: 45,
  },
  {
    id: "plasma",
    name: "Dual-Arc Electro-Plasma",
    description: "An eco-friendly, electronic dual-arc plasma bridge generated at 10,000V. Windproof, silent, futuristic, and fully rechargeable via USB.",
    colorHex: "#9B51E0",
    priceModifier: 60,
  },
];

export const FONTS: FontDetails[] = [
  {
    id: "serif",
    name: "Garamond Serif (Traditional Roman)",
    cssClass: "font-serif tracking-widest uppercase italic",
  },
  {
    id: "script",
    name: "Edwardian Script (Calligraphic Elegance)",
    cssClass: "font-serif italic tracking-wide lowercase first-letter:uppercase font-normal scale-110",
  },
  {
    id: "mono",
    name: "Fira Mono (Minimalist Technical)",
    cssClass: "font-mono tracking-wider uppercase",
  },
  {
    id: "sans",
    name: "Inter (Contemporary Geometric)",
    cssClass: "font-sans tracking-[0.25em] font-light uppercase",
  },
];

export const PRODUCTS: LighterProduct[] = [
  {
    id: "imperator",
    name: "Le Grand Imperator",
    tagline: "The Sovereign Sound of Place Vendôme",
    description: "Widely regarded as the pinnacle of accessories, Le Grand Imperator features a beautifully engineered vertical double-ignition barrel. Closing the lid produces our signature 1.4kHz crystal 'ping' sound that signals elite pedigree in any room.",
    price: 950,
    finishes: ["gold", "silver", "emerald"],
    flames: ["candle", "jet"],
    weight: "145g",
    dimensions: "62mm x 37mm x 11mm",
    fuel: "Premium Pure Butane Gas",
    ignition: "Traditional Flint & Roller Wheel",
    sound: "Pure resonant crystal 'ping' (1.4kHz, 2.4s decay)",
    sku: "LXP-IMP-950",
    story: "Created to celebrate historical French metallurgy, the Imperator incorporates a physical soundboard integrated inside the lid, allowing the gold to sing as it is flipped open.",
    popularity: 88,
    images: ["https://images.unsplash.com/photo-1595556164301-44755106e6bf?q=80&w=600&auto=format&fit=crop"],
    category: "Paris Heritage"
  },
  {
    id: "stealth",
    name: "Obsidian V-12 Stealth",
    tagline: "Aerodynamics & Laser Windproofing",
    description: "A triumph of modern industrial engineering. Designed with aeronautic airflow vents to withstand gale force drafts. Flipped open by pressing a secure knurled trigger, launching a pressurized double jet stream instantly.",
    price: 780,
    finishes: ["obsidian", "damascus"],
    flames: ["jet", "plasma"],
    weight: "112g",
    dimensions: "68mm x 40mm x 13mm",
    fuel: "Refined Liquid Isobutane",
    ignition: "Electronic Piezoelectric Trigger",
    sound: "Deep hydraulic mechanical latch click",
    sku: "LXP-STH-780",
    story: "Crafted for high-altitude explorers, the V-12 utilizes a laser jet system that remains stable even at sub-zero temperatures and altitudes of up to 4,500 meters.",
    popularity: 74,
    images: ["https://images.unsplash.com/photo-1615397349754-cfa2066a298e?q=80&w=600&auto=format&fit=crop"],
    category: "Modern Stealth"
  },
  {
    id: "dynasty",
    name: "The Dynasty Urushi",
    tagline: "The Living Polish of Natural Japanese Resin",
    description: "A gorgeous cross-cultural masterpiece combining S.T. Dupont style heavy brass frames with classical Japanese Urushi lacquer painting. The organic green lacquer is highly tactile, warming up to the touch of your palm.",
    price: 1250,
    finishes: ["emerald", "gold"],
    flames: ["candle"],
    weight: "160g",
    dimensions: "60mm x 38mm x 12mm",
    fuel: "Premium Pure Butane Gas",
    ignition: "Traditional Flint & Roller Wheel",
    sound: "Soft, satisfying wood-lacquer dampened thud",
    sku: "LXP-DYN-1250",
    story: "Each Dynasty lighter spends three months in the workshop of Urushi masters, undergoing painstaking layering, oven curing, and hand-polishing with charcoal powder to reveal unique gold vein ripples.",
    popularity: 92,
    images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=600&auto=format&fit=crop"],
    category: "Urushi Art"
  },
  {
    id: "archon",
    name: "Sterling Archon 925",
    tagline: "Artisanal Hand-Etched Sculptural Heritage",
    description: "Hewn from solid, heavy Sterling Silver blocks, the Archon is hand-etched by a single artisan who carves classical baroque scrolls into the precious metal, assuring that no two pieces are ever identical.",
    price: 1100,
    finishes: ["silver", "damascus"],
    flames: ["candle", "plasma"],
    weight: "172g",
    dimensions: "64mm x 36mm x 12.5mm",
    fuel: "Premium Lighter Petrol / Fluid",
    ignition: "Traditional Flint Wheel & Wick",
    sound: "Metallic, heavy, crisis silver resonance",
    sku: "LXP-ARC-1100",
    story: "Paying tribute to 18th-century royal silversmithing, the Archon feels substantial and satisfyingly heavy in the palm, acquiring a breathtaking silver patina over years of trusted use.",
    popularity: 81,
    images: ["https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600&auto=format&fit=crop"],
    category: "Paris Heritage"
  },
  {
    id: "chronos",
    name: "The Chronos Tourbillon",
    tagline: "Horological Grandeur & Mechanical Precision",
    description: "An exquisite hybrid of micro-mechanics and high-jewelry. Features an open-worked skeletal chamber where a decorative tourbillon wheel rotates gracefully in tandem with the mechanical flint roller wheel.",
    price: 1450,
    finishes: ["gold", "damascus"],
    flames: ["candle", "jet"],
    weight: "168g",
    dimensions: "65mm x 39mm x 14mm",
    fuel: "Refined Liquid Isobutane",
    ignition: "Spring-Loaded Lever & Flint Roller",
    sound: "Exquisite triple clockwork gear-wheel click",
    sku: "LXP-CHR-1450",
    story: "Inspired by haute horlogerie, the Chronos is engineered with 42 micro-components including synthetic sapphire windows to view the internal rotating wheel action.",
    popularity: 95,
    images: ["https://images.unsplash.com/photo-1547996160-81dfa63595aa?q=80&w=600&auto=format&fit=crop"],
    category: "Grand Complications"
  },
  {
    id: "cosmos",
    name: "Celestial Cosmos Noir",
    tagline: "Astral Urushi Lacquer & Starfield Dust",
    description: "Adorned with gold leaf foil dust scattered across an intense dark blue and black Urushi natural resin base, this edition mimics the stellar nebula of the deep cosmos. The surface is polished for 120 hours to reflect perfect light.",
    price: 1350,
    finishes: ["emerald", "obsidian"],
    flames: ["plasma", "jet"],
    weight: "152g",
    dimensions: "61mm x 38mm x 11.5mm",
    fuel: "Premium Pure Butane Gas / USB Rechargeable",
    ignition: "Slick Touch-Cap Sensor & Dual-Arc Ignition",
    sound: "Silent electronic plasma hum with a velvet cap closure",
    sku: "LXP-CSM-1350",
    story: "Originally commissioned for a world-renowned astrophysicist, the Cosmos represents the connection between earthly fire and ancient stars, rendered through master Japanese lacquer artistry.",
    popularity: 89,
    images: ["https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?q=80&w=600&auto=format&fit=crop"],
    category: "Urushi Art"
  },
  {
    id: "vanguard",
    name: "Vanguard Sovereign Gold",
    tagline: "Bespoke Geometric Guilloché & Modern Royalty",
    description: "Featuring a striking chevron pattern cut directly into solid brass plated with heavy gold. This geometric design creates a series of reflective prisms that dance in the light as the lighter is handled.",
    price: 1050,
    finishes: ["gold", "silver"],
    flames: ["candle", "plasma"],
    weight: "158g",
    dimensions: "63mm x 37mm x 12mm",
    fuel: "Premium Pure Butane Gas",
    ignition: "Double-action vertical roller wheel",
    sound: "Ultra-sharp 1.5kHz crystal soprano 'ping'",
    sku: "LXP-VAN-1050",
    story: "Representing contemporary royalty, the chevron pattern is hand-turned using an original 1920s rose-engine lathe to guarantee high-precision optical reflection.",
    popularity: 91,
    images: ["https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=600&auto=format&fit=crop"],
    category: "Paris Heritage"
  }
];

export const REVIEWS: CustomerReview[] = [
  {
    id: "rev1",
    author: "Maximilian V. S.",
    rating: 5,
    date: "June 12, 2026",
    title: "An Unrivaled Masterpiece",
    comment: "The ping of the Grand Imperator is acoustic perfection. Truly, it turns a simple daily routine into a ceremony of class. I had mine engraved in Garamond Serif with my initials, and it receives quiet nods of approval from anyone who appreciates fine craft.",
    verified: true,
    likes: 42,
    avatarInitials: "MS",
  },
  {
    id: "rev2",
    author: "Dr. Evelyn Wright",
    rating: 5,
    date: "July 02, 2026",
    title: "Indestructible Technical Perfection",
    comment: "The V-12 in Damascus Steel is a rugged marvel. The cobalt waves are beautiful, and the double jet torch is impervious to heavy winds during offshore yachting. It feels substantial, precise, and completely secure.",
    verified: true,
    likes: 19,
    avatarInitials: "EW",
  },
  {
    id: "rev3",
    author: "Kenji Tanaka",
    rating: 5,
    date: "April 28, 2026",
    title: "Living Art In The Hand",
    comment: "The Dynasty Urushi's deep emerald emerald sheen is mesmerizing. It warm-starts when held, reflecting light with amazing depth. Sébastien's suggestion to pair it with a gold classical flame was spot on.",
    verified: true,
    likes: 27,
    avatarInitials: "KT",
  },
];
